  alias TicketAgent.{
    Account,
    Class,
    CreditCard,
    Event,
    Listing,
    ListingImage,
    ListingTag,
    Order,
    OrderDetail,
    Random,
    Repo,
    Teacher,
    Ticket,
    TicketRegistration,
    User,
    UserCredential,
    WebhookDetail
  }