ExUnit.start()
# Ecto.Adapters.SQL.Sandbox.mode(TicketAgent.Repo, :manual)
{:ok, _} = Application.ensure_all_started(:ex_machina)
Mox.defmock(TicketAgent.PdfGenerator.Mock, for: TicketAgent.PdfBehaviour)
Application.put_env(:ticket_agent, :pdf_generator, TicketAgent.PdfGenerator.Mock)